### ISSUE TITLE
Add input to allow specifying the retype license key

### ISSUE THREAD

**Issue by fabriciomurta** [fabriciomurta/ragha-build#3]
The license, in general, should be stored as a secret;

**important:** remove/mask the license key as soon as the build completes to avoid leaking the license to subsequent steps

This feature likely depends on #1.

**Comment by geoffreymcgill** [comment]
See issues:
New --license build command arg https://github.com/objectdotnet/retype-app/issues/474
New -- build command args https://github.com/objectdotnet/retype-app/issues/475

**Comment by fabriciomurta** [comment]
With #1 implemented, it was a simple change to add support to specify the license key via input parameters.

**Comment by fabriciomurta** [comment]
This issue has been transferred to retypeapp/action-build#3.
